handlers = java.util.logging.ConsoleHandler, org.yamcs.logging.WatchedFileHandler
org.yamcs.logging.WatchedFileHandler.level = ALL
org.yamcs.logging.WatchedFileHandler.filename = /var/log/yamcs/yamcs.log
org.yamcs.logging.WatchedFileHandler.formatter = org.yamcs.logging.CompactFormatter
org.yamcs.level = CONFIG
